---
- name: Add multiple license using loop
  hosts: localhost
  vars: 
    login: &login
      username: "{{username}}"
      password: "{{password}}"
      hostname: "{{cluster}}"
      https: true
      validate_certs: false
  tasks:
    - include_vars: vars.yaml
    - name: add license
      netapp.ontap.na_ontap_license:
        <<: *login
        state: present
        license_codes: "{{ item }}"
      loop: "{{lookup('file',licensefile).splitlines()}}"
      register: ladd
    - debug:
        msg: "{{ladd}}"

