---
- hosts: localhost
  vars:
    login: &login
      username: "{{username}}"
      password: "{{password}}"
      hostname: "{{cluster}}"
      https: true
      validate_certs: false
  tasks:
  - include_vars: vars.yaml
  - name: Get Cluster Info
    na_ontap_info:
      <<: *login
      gather_subset: all
    register: udisk
  - debug:
      msg: "{{udisk}}"


